# move_base common parameters
# + 2021 Tsudanuma Challenge
# + 2021 Tsukuba Challenge
# Configuration by NaokiTakahashi12
DWAPlannerROS:
  holonomic_robot: false
  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  acc_lim_trans: 1.0
  max_vel_trans: 0.6
  min_vel_trans: 0.1
  max_vel_x: 0.8
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 1.0
  min_vel_theta: 0.1

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true
  theta_stopped_vel: 0.01
  trans_stopped_vel: 0.01

  sim_time: 1.5
  sim_granularity: 0.025
  angular_sim_granularity: 0.1
  vx_samples: 10
  vy_samples: 10
  vth_samples: 20

  path_distance_bias: 0.6
  goal_distance_bias: 1.0
  occdist_scale: 0.3
  twirling_scale: 0.0
  forward_point_distance: 0.825
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid_pc: false
  publish_traj_pc: false
  
  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.2
  prune_plan: true
  use_dwa: true
  restore_defaults: false
